version: "3"

services:
  mongodb:
    image: mongo
    container_name: drewrundev_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: andrewxdp
      MONGO_INITDB_ROOT_PASSWORD: andrewxdp993
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
